excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Pharmacy/Resources
disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
- identifier_name
- type_name
